### ISSUE TITLE
Failed tests on JRuby and Linux

### ISSUE THREAD

**Issue by junaruga** [guard/listen#449] opened 2018-06-08 15:41 UTC
Right now unit tests are failed on the combination of JRuby and Linux.
https://travis-ci.org/guard/listen/builds/388150615

For example below test case that is one of failed test cases.

```
  1) Listen with one listen dir force_polling option to false when :ignore is *ignored_dir* when :ignore is bar.rb when :only is *.rb should process addition of "file.rb"
     Failure/Error: it { is_expected.to process_addition_of('file.rb') }
       expected {:modified=>[], :added=>[], :removed=>[]} to include addition of file.rb
     # ./spec/acceptance/listen_spec.rb:231:in `block in (root)'
     # ./spec/acceptance/listen_spec.rb:17:in `block in (root)'
     # ./spec/support/fixtures_helper.rb:20:in `fixtures'
     # ./spec/acceptance/listen_spec.rb:17:in `block in (root)'
```

However when I ran below command to run the target test case only, the case was passed even on the combination of JRuby and Linux.

```
$ bundle exec rspec spec/acceptance/listen_spec.rb:231
```

See my Travis CI for debug: https://travis-ci.org/junaruga/listen/builds/389763418

Is this fact hint to fix the issue for you?

**Comment by junaruga** [comment] 2018-06-20 12:48
https://travis-ci.org/guard/listen/builds/388150615
It looks current build fixes the test failure. But there are still errors by `simplecov`.

**Comment by junaruga** [comment] 2018-06-29 22:35
Umm? `simplecov`'s error has been already disappeared and there are the test failures on master branch's Travis CI again.

**Comment by eli-darkly** [comment] 2018-11-01 18:59
I have no idea if this is related, but I'm also seeing intermittent failures on JRuby 9.1.17 + Ubuntu. The symptom is that a modification to a file in a watched directory just isn't detected (although sometimes it does work). The modification was made at least 1 second after the listener was started, so I don't think the problem would be related to file time resolution.

It's always worked correctly for me on all non-JRuby versions, and also on JRuby 9.2.0.

**Comment by eli-darkly** [comment] 2018-11-02 18:48
That makes me suspect that the problem is not actually in the file-watching logic, but in the `Processor` - like maybe it does not get woken up from its sleep when an event is added. But I looked through the fixed issues from the JRuby 9.2 release but couldn't find anything related to thread scheduling or sleeps, so I don't know if that makes sense.

**Comment by ColinDKelley** [comment] 2020-11-03 22:48
There were race condition bugs in the `Processor` where it might call `thread.wakeup` before the thread called `sleep`. When that happened, changes would be missed. That might explain this bug. These race conditions are fixed in #481 , which will be released shortly in v3.3.

@eli-darkly Any chance you could try `v3.3.0.pre.2` and see if it fixes this issue?

**Comment by ColinDKelley** [comment] 2020-11-03 22:49
Or maybe it's sufficient that the Travis builds have been green for a while?

**Comment by eli-darkly** [comment] 2020-11-04 20:17
@ColinDKelley - Afraid I can't be of help here, because our project has already dropped support for JRuby 9.1 which was the only platform we'd seen the error in.

**Comment by ColinDKelley** [comment] 2020-11-04 21:29
Ok, thanks @eli-darkly. I think we'll close out this ticket for now. If a new problem comes up, feel free to file a new ticket. We'll at least make sure to keep the CI builds green across the matrix.

**Closed by ColinDKelley** 2020-11-04 21:29 UTC
