### ISSUE TITLE
No method by which current adapter_class selected can be known. 

### ISSUE THREAD

**Issue by puneet24** [guard/listen#334] opened 2015-08-04 17:19 UTC
I am working on gsoc project and using this gem.  I need to know that if listen gem fallback to ''polling" class then at that time I want to use another implementation instead of Polling.

**Comment by e2** [comment] 2015-08-04 18:53
Sure - you'll probably want to fork the project, add your adapter class at the end of this array here:

https://github.com/guard/listen/blob/a41ab6a3e247a4838d69b183f4c1957f16808971/lib/listen/adapter.rb#L10

and if your implementation correctly implements `:usable?`, it will be activated.

Let me know if you have other questions and good luck with the project.

**Comment by puneet24** [comment] 2015-08-10 10:39
I got your point, but is there any way that I can know which adapter_class is currently selected? If I am able to know this, then my task will get simpler because in that case I just need to know when the ''Polling' class is selected then I will perform my implementation , otherwise evented.

**Comment by e2** [comment] 2015-08-10 13:34
Sorry, I misunderstood what you needed.

The class isn't really exposed (yet?), and it's selected here:

https://github.com/guard/listen/blob/master/lib/listen/backend.rb#L12

There's a private attribute to get the current instance of the adapter, although this isn't exposed either:

https://github.com/guard/listen/blob/master/lib/listen/backend.rb#L39

The reason to hide the implementation was because of the idea to allow using different adapters/configurations for different directories in the future, but this won't happen any time soon.

You can probably just call `Adapter.select` and pass a config object created with the options you pass to Listen: https://github.com/guard/listen/blob/master/lib/listen/listener.rb#L37

Or, add a PR exposing what you need and a spec (so the API isn't accidentally refactored out/changed later).

**Comment by puneet24** [comment] 2015-08-10 16:09
Hi, I will list my exact query again for further clarifications.
I want to use Listen only when @adapter_class is not 'Polling'. So I want to know this at the very beginning that if I use Listen then which method is it going to implement? If it is other than Polling then continue with that else I want to implement my way.
So Is there any way by which I can know that on the current system evented is possible using Listen or not?
Is there any kind of method available `Listen_adapter_method_on_current_machine` which will tell me that which method  it is going to on this system, and then I will able to decide what to do next.

**Comment by e2** [comment] 2015-08-10 18:36
Yes, it's exactly what I mentioned - before you use Listen, just use
`Listen::Adapter.select(Listen::Listener::Config.new(listen_opts)) ==
Listen::Adapter::Polling` (something like that).

Then, you can decide if you want to use Listen at all (and pass the same
listen_opts if so).

If listen_opts includes `:force_polling`, the result will always be of
course polling etc.

I don't plan to change that Api so it should continue to work for ages. If
the above doesn't work, let me know.

**Comment by puneet24** [comment] 2015-08-18 12:09
`Listen::Adapter.select()` returns the adapter which is going to be used by listen, but when the project is in   vagrant shared folder then it returns Listen::Adapter::Linux which is not correct because finally it is going to use Polling.
So is there any method by which I can know that finally which adapter is going to be used at the end??

**Comment by fxn** [comment] 2015-08-18 12:41
Let me chime in.

This is for a Rails GSoC. Rails detects if the application has changed by walking the tree of certain directories before each request in development mode. The project implements an evented alternative.

Problem is, in some file systems events are not triggered. So, not even polling is selected. I checked personally in a Vagrant shared folder where the changes are triggered via the host (use-case, the user wants to edit with their editor in the host machine).

So, listen configures the linux adapter because it checks the operating system name against a regexp, but it just won't work in */vagrant*. I suspect other file systems over SSH or networked are not going to play well as well.

Ideally, we'd like to detect that to configure the traditional tree walker per-request and ignore that the project has listen enabled.

**Comment by fxn** [comment] 2015-08-18 12:50
@puneet24 

> when the project is in vagrant shared folder then it returns Listen::Adapter::Linux which is not correct because finally it is going to use Polling

Is that correct? That doesn't match what I see. If you touch a file from within the guest, the block is called. If you do it through the host, nothing happens. If polling was selected we would eventually see the block called.

My hypothesis is that listen `selects()` the linux adapter based on the regexp, and there is no further fallback.

**Comment by puneet24** [comment] 2015-08-18 13:01
In my case when I have kept the project in vagrant shared folder then all tests were passing but it returned the Linux adapter.  
As we know that evented will not work in case of vagrant shared folder then from this observation I assumed that it might fallback further to Polling because tests were passing.

**Comment by fxn** [comment] 2015-08-18 13:36
(Mentor hat on): when investigating stuff this complicated it is better to remove as many variables as possible. For example, I did these tests running:

```
ruby -rlisten -e 'l = Listen.to("/vagrant/test") {|*args| p args}; l.start; sleep'
```

within the virtual machine. If I see something printed, it's being called. See?

**Comment by fxn** [comment] 2015-08-18 14:10
@e2 let me write a summary of our ideal algorithm, assuming the *Gemfile* of the application loads `listen`:

```
if listen select()s Polling
  configure the traditional Rails monitor
else
  instantiate a listener
  if the listener is not going to work for the given config
    stop the listener
    setup the traditional Rails monitor
  end
end
```

So, there are two needs intermixed:

One is that we do not want polling, because our use-case is per-request and polling once at the right time is better for us. For that, we are using `select` in the provisional patch.

The other one is to detect if `listen` selected an adapter that is not going to actually detect changes. I am not even sure detecting that is within the scope of `listen`, maybe is the user who would be responsible for listening to events where events are fired.

But on the other hand the polling backend kind of has that role, isn't it. It's a fallback.

No idea about what is doable, or what makes sense... thought about asking you guys since I am sure you've thought about these corner cases.

**Comment by e2** [comment] 2015-08-18 15:24
Thanks guys for explaining...

Listen tries to use an optimized backend if the OS supports it and the gem is available. E.g. If we're on Windows and the 'wdm' gem is available, the wdm gem is used, or Listen falls back to polling. Otherwise, Listen just matches the gem to the OS (OSX -> rb-fsevent, Linux -> rb-inotify, BSD -> rb-kqueue).

Of course this has nothing to do with the actual folder - on Virtual Machines, if you have a shared folder, you can't listen to changes in folders, because often any changes are propagated over the network upon request (not via a "push").

This means - for Listen to work, the FOLDER listened to has to support optimized listening - and I don't know of a way to detect this. You can e.g. have a FUSE filesystem on Linux that has a "noop" for inotify hooks, and there's no way for Listen to detect that, without scanning mount points and having a database of ALL the possible filesystems out there.

Also, since a user can mount ANY filesystem in ANY directory tree at ANY time, it would be ridiculously complex to support all such cases - except if we have Polling as the default.

In short - anything besides polling won't work over the network (VM folders, SSHFS, etc.), and Listen has no way to detect this, even on Linux.

So the adapter on Linux will always be "Linux" unless the user provides the "force_polling" option (set to "true").

To be on the safe side, you can "force polling" by default - and let the user choose the optimized adapter if they want - because only the user will know if a folder supports listening (e.g. by reading the Wikipedia or testing manually).

Another option would be to create a test file within a certain period of time of listening, and see if an event came in - but this may fail if the project is on a read-only filesystem, etc. No event means reverting to polling, etc. Still you'd need to test every folder in the tree like this to "be sure".

(I could accept a PR with this kind of test, if it makes things any easier.)

I hope that helps - sorry, but filesystem monitoring is a hair-raising nightmare. An alternative is using Listen in TCP mode - where the server listens for changes on the REAL filesystem, and sends those changes to the client (which creates the network filesystem READ requests when attempting to read the actual file).

I am researching ways to make Listening to files easier over the network, but this would be a GSoc project in of itself.

Summary: Listen can't detect whether a given folder/mount point can be listened to optimally or if it needs Polling.

**Comment by e2** [comment] 2015-08-18 15:37
One last thing: the "best" scenario would be to mount a directory inside the VM, as a local drive/mount-point on the host - as long as this VM drive would implement filesystem monitoring on the host.

I'm not aware of any VM implementation that provides such a "full-featured" mountable "VM drive" (the reverse of a "shared host folder" mounted on the client) - but if anyone serious about getting filesystem monitoring working flawlessly on a VM should pursue this option. 

It would probably seriously affect VM filesystem performance, though - so I'm guessing it will take years before that ever happens.

The other option is network filesystems with kqueue/inotify - but AFAIR that idea included lots of problems with lags, timeouts, etc.

A third option is to open a socket and listen for events - and have the text editor send an event after a file is modified/saved. Much faster than polling, but less reliable (and has it's own share of problems).

**Comment by fxn** [comment] 2015-08-18 15:39
@e2 awesome, that's really helpful because it tells us not to pursue that path and think about alternatives.

I believe the test via a dummy file could still be brittle because, according to my tests, in the case of the default Vagrant shared folders changes originated by the guest *do* fire events! Only changes originated by the host do not (even retrieving the files in the guest, I guess that is somehow out of the notification system, but don't really know what's really happening behind the scenes).

@puneet24 I think we have what we needed to know, can continue in Basecamp.

@e2 thanks a lot for your detailed reply, this can be closed :smile:.

**Comment by e2** [comment] 2015-08-18 15:52
@fxn - the `LISTEN_GEM_DEBUGGING=2` environment variable can show which backend is chosen, which events it's getting (if any), etc. 

As for how shared folders are implemented, I doubt VMs actually physically watch the host directory - they just handle file read/write requests WITHIN the VM - which means inotify can work within the VM, but those events aren't merged without outside (host) events which are host-OS specific. 

Otherwise, e.g. the VM would have to translate e.g. kqueue events on a BSD host to simulate inotify events inside the VM running Linux - and merge them with the inotify events received by the kernel INSIDE the VM.

You'd basically need the host OS talking to the VM OS directly below the filesystem layer for this to work, which breaks the whole idea of isolation.

**Comment by fxn** [comment] 2015-08-18 16:00
Yeah, but there's a missing piece in my head (because I only have a conceptual model of this stuff, if I knew how it works I could surely put my finger on the wrong assumption :).

If I have listen watching a shared folder in the guest, I add a file via the host, and I run ls(1) in the guest, the file is there and the operating system has been able to see it. Why is it not able to fire an event whenever it notices the new file is there?

**Comment by e2** [comment] 2015-08-18 16:06
Because the `ls` creates the request (dir entry/open) - and that's likely when the dir is fetched from the host. Network folders are usually request based - the local cache is probably only used once a hit is confirmed. 

I'm not sure about the exact rules for cache, but it seems to me either you risk inconsistency bit time, or the cache is only for data in some cases (and not directory entries). Just guessing here based on articles I read ages ago - I have no idea how today's implementations actually work.

**Comment by e2** [comment] 2015-08-18 16:28
Personally, I'd implement the socket in Rails for listening to "reload" events (or having a dev-only HTTP/API endpoint for doing that) - this makes filesystem monitoring a secondary problem, instead of a primary one. And it gives more flexibility on network/VM setups.

(Could be implemented as a Rails engine).

Another option is storing source files in a database - usually DBs (e.g. PostgreSQL/Redis) have a pub/sub mechanism. Just as an idea.

**Comment by fxn** [comment] 2015-08-18 16:49
Not sure I understand the solution with a socket. Can you elaborate please? Is that related to the TCP feature not yet supporte in 3.x.

Oh, since we are on it, what does it mean "Don't use a OSX (because it uses an expensive "half-polling" mode)"?

**Comment by e2** [comment] 2015-08-18 17:21
Yes, it's related to the TCP feature - instead of using filesystem monitoring, Rails could just create a socket for clients to open and send file change messages (or an engine mountable on some development env-only endpoint). 

So, a developer could have an editor hook which sends a message to this socket with the name of the changed file - and Rails would reload that file. This would also solve network problems, because if a file is modified on the host and a message is sent to the socket, Rails in the VM would reload the file - so there would be no need for filesystem monitoring.

As for OSX, and what I call "half-polling", it means on OSX a workaround is used where only "vague" directory events are reported - and Listen scans those directories for changes manually. I'm not an OSX guy, but AFAIR this was because not all OSX versions supported file tracking (only directory tracking) and even when enabled, too many file-based events flooded Listen.

The drawback is that on OSX folders can be unnecessarily scanned multiple times, and due to HFS timestamp granularity, occasionally MD5 sum hashing is done to check if files really changed. This means potentially high CPU usage if files inside a directory are frequently modified and there's a large file inside.

(As a sidenote, you can potentially hit theses MD5 sum checks on Linux given a FAT filesystem, though MD5 hashing is too ridiculously fast in Ruby on Linux to even notice, while using FAT for filesystem watching is too rare to bother being concerned about).

You can think of Listen as one big OSX workaround/hack. Again, I don't use OSX personally, so I'm a bit "afraid" to optimize the OSX-specific paths in Listen, in fear of breaking things for OSX users.

Cross-platform file listening is basically just one big freak show - probably works best on Linux and ironically Windows. OSX support could be improved, but it's not an itch I have personally.

Still, OSX in it's current state is probably a lot faster than Polling, even though changes in a root file folder may cause multiple directories to be traversed (potentially the whole project).

(I actually put a lot of work into simplifying Listen in version 3.x - just so the OSX issues can be worked out with less complexity in the way).

One note though - for performance testing it's best to use large Rails projects with complex directories/trees (usually with tons of assets). It may turn out that the overhead on OSX is bigger than the gain over standard Rails monitor.

**Comment by fxn** [comment] 2015-08-18 19:32
In what sense are events vague in FSEvents? I am looking at the example code in the README of https://github.com/thibaudgg/rb-fsevent and apparently you are just told "something happened in the directories passed to the block" and you need to figure out what?

**Comment by e2** [comment] 2015-08-18 21:07
That's what I meant by "vague" - Fsevent tells me "something in this directory changed" and Listen has to do the heavy lifting to work out which file(s) actually changed (if any) . Obscenely vague compared to inotify, where I'm properly notified about which files were renamed or moved. This is why it's like polling - the only improvements being: no scanning when no changes happen, and not all folders are scanned every time. 

For this GSoC project, if you only need to know if directories changed, Listen probably isn't a perfect choice (since it deals only with files and not directories). 

You can check the Guard wiki page for Guard alternatives - there may be some other implementation ideas out there which may be a better / simpler fit.

There's an "OSX" simulation mode in the Linux adapter in Listen, but I never got it working identically (to simulate the same events as Fsevent for the same filesystem changes). If you want to just know about directories changed, then you could then pretty much just use the bare Listen adapters as an option.

Hope that explains things a bit.

There's some ongoing work to implement "filesystem snapshots" - just to extract some of the complex logic to a separate gem,  but there's no ETA on that yet. 

Otherwise, I wouldn't rely too much on Listen for end to end consistency at all times. You may want to checkout Facebook's watchman project as an alternative.

It's hard to expect any guarantees from a filesystem to begin with (Listen is more about quickly responding to a specific set of tracked changes to files - with extra magic to support complex editor scenarios (temp files, backups, renames, slow writes, etc.).

Let me know if you need anything else.

**Comment by e2** [comment] 2015-10-06 12:11
I'm closing this - please reopen (or open a new issue) if needed.

**Closed by e2** 2015-10-06 12:11 UTC
