### ISSUE TITLE
100% cpu usage with Compass

### ISSUE THREAD

**Issue by thany** [guard/listen#295] opened 2015-03-06 09:35 UTC
Listen *might* be responsible for consuming 100% CPU time (on one core) when used by Compass. Unfortunately, I have neither the know-how nor the proper tools to dig into this problem, but I've seen reports of listen being the cause of the 100% CPU problem. So, I thought I'd mention it here, and hopefully someone is able to get to the bottom of this and have a fix ready.

Here's the issue: https://github.com/Compass/compass/issues/1817

Versions:
* Listen 2.8.5
* Compass 1.0.3
* Sass 3.4.13
* Gem system 2.4.6
* Ruby 2.1.3p242 x64
* Windows 7 x64

I've got a couple other gems installed, but I'm not sure which might be relevant. Post them? Lemme know. Need more info? Feel free to ask away :)

**Comment by e2** [comment] 2015-03-06 09:51
@thany - there could be many reasons.

First, follow this: https://github.com/guard/listen/wiki/Quickfixes%2C-known-issues-and-workarounds (the `LISTEN_GEM_DEBUGGING=1` is especially important).

Then, follow this: https://github.com/guard/listen/wiki/Troubleshooting.

What I need is output from having `LISTEN_GEM_DEBUGGING=1` - that usually helps find the cause no matter what the problem is.

It might help if you can create a small repo reproducing the problem (because often it's a project-specific problem).

**Comment by e2** [comment] 2015-03-06 09:58
@thany - oh, and I forgot that sass forces polling on Windows - if you have a large project, this could be slow (because it's scanning the whole project tree every fraction of a second or so).

Ideally, make sure your `compass.rb` file is set to watch only the stylesheets input and output directories.
e.g. if you have:

```ruby
project_path = File.expand_path(File.join(File.dirname(__FILE__), '..'))
```

the `'..'` may be causing compass to watch you're whole project or even your whole home folder! (so your compass config and/or project layout may be the problem).

**Comment by thany** [comment] 2015-03-06 14:20
Hmm, why would Sass force polling when Windows has had a perfectly fine API for being notified of mutation for at least 15 years?...

**Comment by thany** [comment] 2015-03-06 14:23
Could this be part of the problem?
```
>set LISTEN_GEM_DEBUGGING=1
>listen -v
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- tho
r (LoadError)
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/listen-2.8.5/lib/listen/cli.rb:1:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/listen-2.8.5/bin/listen:4:in `<top (required)>'
        from C:/Ruby21-x64/bin/listen:23:in `load'
        from C:/Ruby21-x64/bin/listen:23:in `<main>'
```

**Comment by e2** [comment] 2015-03-06 15:32
> Hmm, why would Sass force polling when Windows has had a perfectly fine API for being notified of mutations for at least 15 years?...

Back in 2012 that seemed true: https://github.com/sass/sass/commit/a3031856b22bc834a5417dedecb038b7be9b9e3e.

Personally though, I don't use Windows (I avoid it like the plague), so I wouldn't know - if you find that to be false, you can open an issue for sass (I don't know if there are other reasons polling is forced on Windows). 

You can take a look at the `wdm` gem if you're curious - it probably hasn't been maintained for years.

> Could this be part of the problem?

You'll need to install `thor` manually - `thor` isn't specified as a dependency, because it's only needed for the listen binary (which probably should be a separate gem) - you don't need it for compass itself. In most use cases listen is used as a library, and `thor` version mismatches have caused issues in the past.

**Comment by e2** [comment] 2015-10-06 12:06
I'm closing this since Listen 3.x is recommended and should cause a lot less problems.

Do open a new issue if you get any related problems on Listen 3.x.

**Closed by e2** 2015-10-06 12:06 UTC
Labels: Waiting for user
